apiVersion: v1  
items:
- apiVersion: v1
  kind: Service 
  metadata:     
    creationTimestamp: "2022-02-27T15:33:00Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "209"
    uid: c8e75880-87ae-416f-b376-295533fd6675
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-03-07T05:00:45Z"
    labels:
      app: nginx
    name: nginx
    namespace: default
    resourceVersion: "534487"
    uid: 31cfd837-6d5b-4734-bbba-1fd2e3d1a07a
  spec:
    clusterIP: 10.109.244.99
    clusterIPs:
    - 10.109.244.99
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""