apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-03-07T08:31:10Z"
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "552070"
  uid: 6c12acc7-1e6e-4c12-93e8-1d46a7314381
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.146.234
  clusterIPs:
  - 10.111.146.234
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31582
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}